### ISSUE TITLE
Setting up android for use in remote operation [TRACKER]

### ISSUE THREAD

**Issue by Moonwards** [moonwards1/Moonwards-Virtual-Moon#1004]
There is an android meant for use on the surface, being operated remotely instead of people going outside themselves in spacesuits. A series of tasks need to be done to get that in the game.
- [x] Complete armature
- [x] create walk animation
- [x] create kiosk where players activate remote operation #1006
- [x] set up controls and scripts so that players can play at operating the androids #1007
- [x] place androids in a few exterior locations, and perhaps also in currently inaccessible habs - Long Dome and the Spaceport Terminal
