### ISSUE TITLE
Complete audio tour

### ISSUE THREAD

**Issue by Moonwards** [moonwards1/Moonwards-Virtual-Moon#270]
Most of the elements of this are done but they need to be integrated together and polished. See #390
- [ ] Integrate the outdoor tour with the indoor tour
- [x] replace audio clips with new versions and add clips for outdoor portion
- [x] polish look and behavior of markers
- [ ] test and refine
- [x] Separate portions of audio tour paths in different scenes into that scene, for proper lighting.

**Comment by Moonwards** [comment]
@Zach777 There are a few clips that are meant to play during the long walks between points on the tours. Do you have ideas on how that could be handled?

**Comment by Moonwards** [comment]
@Zach777 Could you set it up so that the AudioTourPaths are hidden after a player completes the tour?

**Comment by Moonwards** [comment]
@Zach777 Come to think of it, probably it would be better if each path only shows up after the previous marker has been activated, and hides when the next marker is activated. Which brings back the matter of how to integrate the audio that is intended for between markers. If a player has activated the previous marker, and passes through a zone placed on the path to the next marker, then that audio could play. Would that work?

**Comment by Zach777** [comment]
Yes. Although we would need to come up with another way to show the path. My first guess would be to make a Path3D that traces out the path to the Spheres. Than use some sort of draw() call to create a glowing outline that traces the path.
 Would you rather have one glowing line or a pulse that originates at the orb you are listening to and travels to the next one?

**Comment by Moonwards** [comment]
I think one glowing line, because otherwise we have to make sure the pulse is near the player.

So do you need a path that's different from the models I made? I don't know what sort of file to export from Blender to get you what you need.

**Comment by Zach777** [comment]
Leave the path as is for now. I will use that to guide whatever it is that I need.

**Comment by Moonwards** [comment]
I'm going to close this card and move the remaining task - setting up glowing paths - to a new card.
