### ISSUE TITLE
[TRACKER] Rig the Athlete Rover completely

### ISSUE THREAD

**Issue by Moonwards** [moonwards1/Moonwards-Virtual-Moon#291]
The Athlete rover has one basic animation and a rather inadequate rig. 
It will eventually have much more extensive ability. It will manipulate things with its front legs and hand-like extensions, use its own tools, and be able to traverse any terrain or climb. It should be able to move any way an insect with wheels could. Ultimately, it should be able to split into two rovers with three legs.
- [x] redo rig so that joints move properly through their whole range of motion
- [x] set up the ability to move on slopes - a simple system at first. To descend steep slopes the rover turns sideways.
- [x] set up wheels following the contour / slope of the ground while the body attempts to stay steady
- [x] rig the tool-using arms tucked into each of the two front legs
- [x] it has two small arms on its body that run on tracks. Each has a camera and a light on the end. Rig these.
Blender model: https://github.com/moonwards1/Moonwards-Assets/blob/master/Models/AthleteRover.blend

Reference video showing a prototype of the rover being tested by a NASA team: https://youtu.be/zgozjwyUnnk
Animation by NASA of the rover on the moon: https://youtu.be/Tb0_GNyczCA?t=59

![Screenshot from 2020-06-03 12-26-53.png](https://app.gitkraken.com/api/glo/boards/5e96433deb480d00123f5d87/attachments/5ed7dde19ea51d00111183a2)

![Screenshot from 2020-06-03 12-27-29.png](https://app.gitkraken.com/api/glo/boards/5e96433deb480d00123f5d87/attachments/5ed7dded38b36e0012c37b7a)

![Screenshot from 2020-06-03 12-28-30.png](https://app.gitkraken.com/api/glo/boards/5e96433deb480d00123f5d87/attachments/5ed7ddf6c6b8eb0012d6727d)

**Comment by Moonwards** [comment]
This is now fully and properly rigged in Blender, and has been successfully exported as an ESCN file 

Work in Godot continues.

**Comment by Moonwards** [comment]
@Reousa it occurs to me that making some kind of little terminal

**Comment by Moonwards** [comment]
In order to close this, I'm eliminating the one task that isn't done. Work on the complex movement that will allow the rover to walk, as well as roll on its wheels, isn't planned for the near future and doesn't need any documentation in the issues at this time.
