### ISSUE TITLE
[TRACKER] Make a few key interactables

### ISSUE THREAD

**Issue by Moonwards** [moonwards1/Moonwards-Virtual-Moon#293]
Initial interactive displays need to demonstrate the core concepts, and serve as a guide to participation. 
Each of these should become their own card, but for design purposes are being drafted here first. See also #365

- [ ]~~Rocket display - this exists but should be re-exported as a .glb.~~  This can be used in its previous file format for the time being. See #364
- [ ] A demo of a Melt In Place printer was started, animation of it was planned. This would be a good second interactable. See #369
- [x] The Makers Monument is also detailed already on its own card and is an example of this. In its case, it is intended to expand over time. See #84
- [ ] The Moonwards kiosk also needs a few things. Models are meant to go on its shelves which can be picked up and examined, in which case attached material can also be accessed.
- [ ]  The kiosk is also a good place to offer access to a few videos or slideshows.

**Comment by Moonwards** [comment]
I am now going to split this into separate cards, and identify behaviors they need that can be worked on.

**Comment by Reousa** [comment]
Are these scheduled for the pre-alpha demo btw? If so let's add the milestone label

**Comment by SiudaPL** [comment]
I'm currently working on code aspect of the *Displays* - the interaction API. The *animations* and later on, *slides* can be also assigned to someone else.

**Comment by Moonwards** [comment]
I'm giving up on a few of these things for now.

**Comment by Zach777** [comment]
Which ones are you giving up on?
