### ISSUE TITLE
[TRACKER] NPC Editor features

### ISSUE THREAD

**Issue by yaelatletl** [moonwards1/Moonwards-Virtual-Moon#450]
# Editor
- [x] Behavior trees are editable
- [x] Behavior trees can be saved
- [x] Behavior trees can be opened (editor)
- [x] Behavior trees can be loaded (as states)
- [x] States that represent each BT 
- [x] The State machine can be saved
- [x] The State machine can be loaded (as the complete NPC behavior)
- [x] The State machine can be opened (editor)
- [x] Any other NPC information is stored in the SM file 
- [x] Sounds can be attached or referenced in editor
- [x] The editors can be accessed in the Godot Engine Editor
- [x] The whole system is an addon
- [x] Shortcuts to add different nodes in-editor
# Dialog System
- [x] Linear dialogs
- [x] Let the player answer
- [x] Dialogs based on clicking buttons
- [x] Dialogs based on code words
- [x] Branching dialogs
- [X] Have an editor for the dialogs
- [x] Dialogs can be loaded in their editor
