### ISSUE TITLE
[TRACKER] Set up improved materials on large surfaces

### ISSUE THREAD

**Issue by Moonwards** [moonwards1/Moonwards-Virtual-Moon#481]
This set of materials will grow with time. The current approach is to create fully textured materials only for large areas, and for small items, use pure colors that use roughness, metalness, and specular for any subtle texture effects. (For this to look good, light effects have to work well.)

Large areas receiving full texture treatment:

- [x] #479 - Habitat ground floors (moss with scattered plants)
- [x] #474 - Habitat walls (a mix of a mottled rough glaze on the wall, and wall covering of moss and ivy)
- [x] #473  - Factory Foundations and Launch Pads (cast stone  with a roughened surface to aid traction)
- [x] #472 - Road (poured molten rock with rock chunks)
- [x] #471 - Lunar terrain (small scale detail for Lalande)

Refinement and adapting
