### ISSUE TITLE
Further graphics work possibilities

### ISSUE THREAD

**Issue by Moonwards** [moonwards1/Moonwards-Virtual-Moon#501]
- [x] Setting up accessible parameters for normals and roughness for existing shader materials
- [x] Swimming pool water shader
- [x] Documenting shader materials - notes on use, organization of nodes
- [ ] Getting the Earth to reflect in mirrors outside hexpane windows (#338)
- [x] Alternate wall-with-plants material where the proportion of the wall that is plant cover can be adjusted
