### ISSUE TITLE
[TRACKER] Playability QA

### ISSUE THREAD

**Issue by Reousa** [moonwards1/Moonwards-Virtual-Moon#509]
This is a list of things to go over, test, and iterate on if necessary.
Will be expanded into issues as we go over things mentioned below, things will only be checked here once completely approved.

- [x] Billboard functionality - could use the arrows being moved
- [x] Makers monument - needs new audio clips
- [x] Realistic player movement and jump speed
- [x] Athlete Rover & Docking
- [x] Entering the passenger pod
- [x] Interactable Tooltips
- [x] Playability over network, on a live server
- [x] Climbing stairs
- [x] Remove ability to move while in the air
- [x] Fix rendering of Moon Town Master > Road - Issue #540
- [x] Fix issue using F to take control of a Rover

**Comment by Zach777** [comment]
What do you mean by using F to take control of the Rover, @Reousa ?

 I will see what I can do with billboard presentation and all it's glitchiness.

**Comment by Zach777** [comment]
@Moonwards The Maker's Monument audio has been added correct?

**Comment by Moonwards** [comment]
Yes
