### ISSUE TITLE
[TRACKER] Applying materials and Model Fixes

### ISSUE THREAD

**Issue by Moonwards** [moonwards1/Moonwards-Virtual-Moon#532]
The branch for this has already been created and has a commit. The work done so far is 
* Airlock Bay - airlocks have been moved so that they are all accessible
* RecHab 1 - stairs edited so they can be climbed
- [x] Rotate Airlock doors so they open upwards
- [x] Fix Carousel stairs (in First Gallery Upper) so they can be climbed
- [x] Thicken walls of Factories and Hangars so they don't display Z fighting
- [x] Remove back face of Solar Thermal mirror sets so they don't display Z fighting
- [x] Determine why large parts of Road in MoonTown Master are showing black and fix - moved to #540
- [x] Apply Road_Asphalt_Shader to all versions of Spaceport Road - had issues, subbed simpler material
- [x] Apply Gallery_Mainwall_Shader to RecHab, First Atrium, and the two Farm Atriums - abandoned
- [x] Create a new materials slot for the floors of the First Atrium and the Farm Atriums - abandoned
- [x] Apply Factory_Foundation_Shader to floors of First Atrium and Farm Atriums, - Abandoned
- [x] Reexport MoonTown Master with the satellite dishes in place on top of the boulders by the First Atrium - Abandoned
- [x] Road width - barely drive-able with Rover, issue # 517
- [x] Add new materials to all LOD levels, where indicated

**Comment by Moonwards** [comment]
@Reousa The only thing here that still merits attention is the Road problem. That problem exists on Master as well as on the Apply materials and fixes branch. Most of the Road in Moon Town Master shows flat black for no reason i can discern.

So, we need to decide if that needs fixing or we are going to leave it for the time being. My feeling is that at this point, possibly even a glaring material issue like that one should be left. There is more than one fundamental problem underlying our repeated issues with materials, and with problems that arise after the reimport of meshes. I feel it may be best to resolve our remaining Pre-Alpha Demo goals and spend no more time on that.

**Comment by Reousa** [comment]
I've given it some investigation, I got varying results, it appears to be related to the shader settings reacting to lighting.
The flat black color I got was on the sides of the road, as in this image (yeah?)
![image](https://user-images.githubusercontent.com/18017673/92620083-8bb9ac80-f2c2-11ea-90df-5d8a05f0faee.png)


Examples of different material settings:
![image](https://user-images.githubusercontent.com/18017673/92619718-2ebdf680-f2c2-11ea-8740-0c8cd713593f.png)

![image](https://user-images.githubusercontent.com/18017673/92619967-6cbb1a80-f2c2-11ea-9ffb-fcc57bac5d7d.png)


This was all tested on master, though I don't have much context of what the material parameters actually do. Could be a shader bug.

**Comment by Moonwards** [comment]
It was working fine and then broke, so it may have to do with Godot clearing settings. It has done that in other cases.

You have to navigate further from the center of town to really see it. Most of the length of the road is black.

![image.png](https://app.gitkraken.com/api/glo/boards/5e96433deb480d00123f5d87/attachments/5f58f95d3d9b050011bc79d4)

**Comment by Moonwards** [comment]
There are issues showing up now that this has been rebased on to master. I'm going to document here the ones i can't fix.

![Screenshot from 2020-09-11 15-30-36.png](https://app.gitkraken.com/api/glo/boards/5e96433deb480d00123f5d87/attachments/5f5bdef83d9b050011bd597c)

The Neighborhood models are displaying as LOD2. A problem that wasn't the same, but similar,

**Comment by Moonwards** [comment]
The exterior airlock doors don't open.

This *might* be related to reimporting the airlock to fix another problem - the hinges on the airlock structure were in the wrong place, a problem that had been fixed previously as well, and that i recall being merged correctly.

![image.png](https://app.gitkraken.com/api/glo/boards/5e96433deb480d00123f5d87/attachments/5f5be6563d9b050011bd5b85)

This may be due to this animation. It hasn't been modified like the Open_Interior animation, which is working.

**Comment by Moonwards** [comment]
It is quite difficult to exit the vertical stairs.

**Comment by Zach777** [comment]
Yeah I noticed the stairs issue. I will make a new issue that says we need to update stairs to handle the new physics.
