### ISSUE TITLE
[TRACKER] Material problem list

### ISSUE THREAD

**Issue by Moonwards** [moonwards1/Moonwards-Virtual-Moon#564]
- [x] LOD! and LOD2 of RecHab1 pool water should be changed to a water material
- [x] #540 Road mesh shows as flat black - may be an issue with mesh, or may be a material issue
- [x] Overlay-1st-Gal-Upper and FGU window materials are culling incorrectly #608

- [x] Lalande-MoonTown material shows distortion due to some sort of problem with Godot's interpretation of the UV map. The issue is being fixed by the Godot team.
