### ISSUE TITLE
[TRACKER] Start Screen rework

### ISSUE THREAD

**Issue by Moonwards** [moonwards1/Moonwards-Virtual-Moon#566]
Here are the menus that need to be part of the start screen:

Main menu - 
Destination, Avatar, Settings, Apps

Destination menu
Main list - Join Main Server, Start Custom Server, Join Custom Server, ip4 address:
secondary list - Downtown, Teacup Crater, Long Dome, Spaceport

Avatar menu
 As is

Settings menu
Controls, Graphics, Audio
each with the most common settings listed there

App menu
Building, Event, Character, Film, Graphic Novel, Collaboration

The current design is below, which is a strong starting point.
It really only needs some refinement to be a bit more balanced and cleaner, and to accommodate the logo better
A draft design needs to be for backgrounds that change every few seconds, those backgrounds will be chosen to match well with the menu.

- [x] #567 - Update avatar customization screen with new models 
- [x] Fix color selector functionality
- [x] Avatar section - Make color picker larger and put 'Gender' and 'Color Slot' side by side to save space
- [x] All menus - Change background to a set of images that change every few seconds #583
- [x] Loading screen also has images that change every few seconds #584
- [x] Destination - Add a list of spawn points, that either loads after a Server option is picked, or is listed beside that list #585
- [x] Update the About screen #588
- [x] Create a settings menu
    - [x] Create a Controls settings submenu #589
    - [x] Create a Graphics settings submenu #590
- [x] Change pose of models in avatar customization screen
![Screenshot from 2020-09-21 11-23-02.png](https://app.gitkraken.com/api/glo/boards/5e96433deb480d00123f5d87/attachments/5f68d53c24316d0011f17b19)

![Screenshot from 2020-09-21-Avatar-Screen.png](https://app.gitkraken.com/api/glo/boards/5e96433deb480d00123f5d87/attachments/5f68d67a3d9b050011c06c4a)

**Comment by Reousa** [comment]
I'll suggest adding "Add ability to rotate character model in customization screen"

**Comment by Moonwards** [comment]
That sounds like it would be good, but it seems like an extra right now. i'd leave it as something we could do if there is time. Perhaps an issue card to go in the 'Backlog' column.

**Comment by Zach777** [comment]
@Moonwards What exactly do you mean by "fix color selector functionality,"?
 Do you mean how you interact with the menu element of color selector? Or do you mean that the color selector choices are not being saved?

 The latter is not a menu thing technically. (I will still work on it if wanted)

**Comment by Moonwards** [comment]
Yes, I meant that the colors selected are not being saved. @Zach777 
Check with @Reousa whether he should work on it or you should.

**Comment by Zach777** [comment]
Is color selection functionality developed enough to check off the fix color selector field? @Moonwards
